# Generated by Django 5.0.8 on 2024-08-26 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_service', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='domain',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
